/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CFApp {
    /**
    * The channel has to be set to link
    */
    'channel': CFApp.ChannelEnum;
    /**
    * Specify the channel through which the payment must be processed.
    */
    'provider': string;
    /**
    * Customer phone number associated with a wallet for payment.
    */
    'phone': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "CFApp.ChannelEnum"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CFApp.attributeTypeMap;
    }
}

export namespace CFApp {
    export enum ChannelEnum {
        Link = <any> 'link'
    }
}
