/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CFAuthorizationRequest {
    /**
    * Type of authorization to run. Can be one of \'CAPTURE\' , \'VOID\'
    */
    'action'?: CFAuthorizationRequest.ActionEnum;
    /**
    * The amount if you are running a \'CAPTURE\'
    */
    'amount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "CFAuthorizationRequest.ActionEnum"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CFAuthorizationRequest.attributeTypeMap;
    }
}

export namespace CFAuthorizationRequest {
    export enum ActionEnum {
        Capture = <any> 'CAPTURE',
        Void = <any> 'VOID'
    }
}
