/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The authorization details are present for payments which go through the preauthorization workflow. Or else this parameter will be null.
*/
export class CFAuthorizationInPaymentsEntity {
    /**
    * One of CAPTURE or VOID
    */
    'action'?: CFAuthorizationInPaymentsEntity.ActionEnum;
    /**
    * One of SUCCESS or PENDING
    */
    'status'?: CFAuthorizationInPaymentsEntity.StatusEnum;
    /**
    * The captured amount for this authorization request
    */
    'capturedAmount'?: number;
    /**
    * Start time of this authorization hold (only for UPI)
    */
    'startTime'?: string;
    /**
    * End time of this authorization hold (only for UPI)
    */
    'endTime'?: string;
    /**
    * Approve by time as passed in the authorization request (only for UPI)
    */
    'approveBy'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "CFAuthorizationInPaymentsEntity.ActionEnum"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CFAuthorizationInPaymentsEntity.StatusEnum"
        },
        {
            "name": "capturedAmount",
            "baseName": "captured_amount",
            "type": "number"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "string"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "string"
        },
        {
            "name": "approveBy",
            "baseName": "approve_by",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CFAuthorizationInPaymentsEntity.attributeTypeMap;
    }
}

export namespace CFAuthorizationInPaymentsEntity {
    export enum ActionEnum {
        Capture = <any> 'CAPTURE',
        Void = <any> 'VOID'
    }
    export enum StatusEnum {
        Success = <any> 'SUCCESS',
        Pending = <any> 'PENDING'
    }
}
