/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CFCardlessEMI {
    /**
    * The channel for cardless EMI is always `link`
    */
    'channel': CFCardlessEMI.ChannelEnum;
    /**
    * One of [\"flexmoney\", \"zestmoney\"]
    */
    'provider': CFCardlessEMI.ProviderEnum;
    /**
    * Customers phone number for this payment instrument. If the customer is not eligible you will receive a 400 error with type as \'invalid_request_error\' and code as \'invalid_request_error\'
    */
    'phone': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "CFCardlessEMI.ChannelEnum"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "CFCardlessEMI.ProviderEnum"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CFCardlessEMI.attributeTypeMap;
    }
}

export namespace CFCardlessEMI {
    export enum ChannelEnum {
        Link = <any> 'link'
    }
    export enum ProviderEnum {
        Flexmoney = <any> 'flexmoney',
        Zestmoney = <any> 'zestmoney'
    }
}
