/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CFCustomerDetails {
    /**
    * A unique identifier for the customer. Use alphanumeric values only.
    */
    'customerId': string;
      /**
    * Customer name.
    */
    'customerName': string;
    /**
    * Customer email address.
    */
    'customerEmail': string;
    /**
    * Customer phone number.
    */
    'customerPhone': string;
    /**
    * Customer bank account. Required if you want to do a bank account check (TPV)
    */
    'customerBankAccountNumber': string;
    /**
    * Customer bank IFSC. Required if you want to do a bank account check (TPV)
    */
    'customerBankIfsc': string;
    /**
    * Customer bank code. Required for net banking payments, if you want to do a bank account check (TPV)
    */
    'customerBankCode': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "customerId",
            "baseName": "customer_id",
            "type": "string"
        },
        {
            "name": "customerName",
            "baseName": "customer_name",
            "type": "string"
        },
        {
            "name": "customerEmail",
            "baseName": "customer_email",
            "type": "string"
        },
        {
            "name": "customerPhone",
            "baseName": "customer_phone",
            "type": "string"
        },
        {
            "name": "customerBankAccountNumber",
            "baseName": "customer_bank_account_number",
            "type": "string"
        },
        {
            "name": "customerBankIfsc",
            "baseName": "customer_bank_ifsc",
            "type": "string"
        },
        {
            "name": "customerBankCode",
            "baseName": "customer_bank_code",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CFCustomerDetails.attributeTypeMap;
    }
}

