/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CFLinkNotifyEntity {
    /**
    * If \"true\", Cashfree will send sms on customer_phone
    */
    'sendSms'?: boolean;
    /**
    * If \"true\", Cashfree will send email on customer_email
    */
    'sendEmail'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sendSms",
            "baseName": "send_sms",
            "type": "boolean"
        },
        {
            "name": "sendEmail",
            "baseName": "send_email",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CFLinkNotifyEntity.attributeTypeMap;
    }
}

