/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CFLinkMetaEntity {
    /**
    * Notification URL for server-server communication. It should be an https URL.
    */
    'notifyUrl'?: string;
    /**
    * If \"true\", link will directly open UPI Intent flow on mobile, and normal link flow elsewhere
    */
    'upiIntent'?: boolean;
    /**
    * The URL to which user will be redirected to after the payment is done on the link. Maximum length: 250.
    */
    'returnUrl'?: string;
    /**
    * Allowed payment modes for this link. Pass comma-separated values among following options - \"cc\", \"dc\", \"ccc\", \"ppc\", \"nb\", \"upi\", \"paypal\", \"app\". Leave it blank to show all available payment methods
    */
    'paymentMethods'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "notifyUrl",
            "baseName": "notify_url",
            "type": "string"
        },
        {
            "name": "upiIntent",
            "baseName": "upi_intent",
            "type": "boolean"
        },
        {
            "name": "returnUrl",
            "baseName": "return_url",
            "type": "string"
        },
        {
            "name": "paymentMethods",
            "baseName": "payment_methods",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CFLinkMetaEntity.attributeTypeMap;
    }
}

