/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CFLinkCustomerDetailsEntity } from './cFLinkCustomerDetailsEntity';
import { CFPaymentURLObject } from './cFPaymentURLObject';
import { CFRefundURLObject } from './cFRefundURLObject';
import { CFSettlementURLObject } from './cFSettlementURLObject';

export class CFLinkOrders {
    'cfOrderId'?: number;
    'orderId'?: string;
    'entity'?: string;
    'orderCurrency'?: string;
    'orderAmount'?: number;
    'orderStatus'?: string;
    'orderToken'?: string;
    'orderExpiryTime'?: string;
    'orderNote'?: string;
    'customerDetails'?: CFLinkCustomerDetailsEntity;
    'payments'?: CFPaymentURLObject;
    'settlements'?: CFSettlementURLObject;
    'refunds'?: CFRefundURLObject;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cfOrderId",
            "baseName": "cf_order_id",
            "type": "number"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "entity",
            "baseName": "entity",
            "type": "string"
        },
        {
            "name": "orderCurrency",
            "baseName": "order_currency",
            "type": "string"
        },
        {
            "name": "orderAmount",
            "baseName": "order_amount",
            "type": "number"
        },
        {
            "name": "orderStatus",
            "baseName": "order_status",
            "type": "string"
        },
        {
            "name": "orderToken",
            "baseName": "order_token",
            "type": "string"
        },
        {
            "name": "orderExpiryTime",
            "baseName": "order_expiry_time",
            "type": "string"
        },
        {
            "name": "orderNote",
            "baseName": "order_note",
            "type": "string"
        },
        {
            "name": "customerDetails",
            "baseName": "customer_details",
            "type": "CFLinkCustomerDetailsEntity"
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "CFPaymentURLObject"
        },
        {
            "name": "settlements",
            "baseName": "settlements",
            "type": "CFSettlementURLObject"
        },
        {
            "name": "refunds",
            "baseName": "refunds",
            "type": "CFRefundURLObject"
        }    ];

    static getAttributeTypeMap() {
        return CFLinkOrders.attributeTypeMap;
    }
}

