/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CFPaymentMethod } from './cFPaymentMethod';

export class CFOrderPayRequest {
    'orderToken': string;
    'paymentSessionId': string;
    'paymentMethod': CFPaymentMethod;
    'saveInstrument'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderToken",
            "baseName": "order_token",
            "type": "string"
        },
        {
            "name": "paymentSessionId",
            "baseName": "payment_session_id",
            "type": "string"
        },
        {
            "name": "paymentMethod",
            "baseName": "payment_method",
            "type": "CFPaymentMethod"
        },
        {
            "name": "saveInstrument",
            "baseName": "save_instrument",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CFOrderPayRequest.attributeTypeMap;
    }
}

