/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CFCustomerDetails } from './cFCustomerDetails';
import { CFOrderMeta } from './cFOrderMeta';
import { CFVendorSplit } from './cFVendorSplit';

export class CFOrderRequest {
    /**
    * Order identifier present in your system. Alphanumeric and only - and _ allowed.
    */
    'orderId'?: string;
    /**
    * Bill amount for the order. Provide upto two decimals. 10.15 means Rs 10 and 15 paisa
    */
    'orderAmount': number;
    /**
    * Currency for the order. INR if left empty. Contact care@cashfree.com to enable new currencies. 
    */
    'orderCurrency': string;
    'customerDetails': CFCustomerDetails;
    'orderMeta'?: CFOrderMeta;
    /**
    * Time after which the order expires. Customers will not be able to make the payment beyond the time specified here. We store timestamps in IST, but you can provide them in a valid ISO 8601 time format.
    */
    'orderExpiryTime'?: string;
    /**
    * Order note for reference.
    */
    'orderNote'?: string;
    /**
    * Custom Tags which can be passed for an order. A maximum of 6 tags can be added
    */
    'orderTags'?: { [key: string]: string; };
    'orderSplits'?: Array<CFVendorSplit>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "orderAmount",
            "baseName": "order_amount",
            "type": "number"
        },
        {
            "name": "orderCurrency",
            "baseName": "order_currency",
            "type": "string"
        },
        {
            "name": "customerDetails",
            "baseName": "customer_details",
            "type": "CFCustomerDetails"
        },
        {
            "name": "orderMeta",
            "baseName": "order_meta",
            "type": "CFOrderMeta"
        },
        {
            "name": "orderExpiryTime",
            "baseName": "order_expiry_time",
            "type": "string"
        },
        {
            "name": "orderNote",
            "baseName": "order_note",
            "type": "string"
        },
        {
            "name": "orderTags",
            "baseName": "order_tags",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "orderSplits",
            "baseName": "order_splits",
            "type": "Array<CFVendorSplit>"
        }    ];

    static getAttributeTypeMap() {
        return CFOrderRequest.attributeTypeMap;
    }
}

