/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CFOrderPayData } from './cFOrderPayData';

export class CFOrderPayResponse {
    /**
    * Payment identifier created by Cashfree
    */
    'cfPaymentId'?: number;
    /**
    * One of [\"upi\", \"netbanking\", \"card\", \"app\", \"cardless_emi\", \"paylater\"] 
    */
    'paymentMethod'?: CFOrderPayResponse.PaymentMethodEnum;
    /**
    * One of [\"link\", \"collect\", \"qrcode\"]. In an older version we used to support different channels like \'gpay\', \'phonepe\' etc. However, we now support only the following channels - link, collect and qrcode. To process payments using gpay, you will have to provide channel as \'link\' and provider as \'gpay\'
    */
    'channel'?: CFOrderPayResponse.ChannelEnum;
    /**
    * One of [\"link\", \"custom\", \"form\"]
    */
    'action'?: CFOrderPayResponse.ActionEnum;
    'data'?: CFOrderPayData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cfPaymentId",
            "baseName": "cf_payment_id",
            "type": "number"
        },
        {
            "name": "paymentMethod",
            "baseName": "payment_method",
            "type": "CFOrderPayResponse.PaymentMethodEnum"
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "CFOrderPayResponse.ChannelEnum"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "CFOrderPayResponse.ActionEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CFOrderPayData"
        }    ];

    static getAttributeTypeMap() {
        return CFOrderPayResponse.attributeTypeMap;
    }
}

export namespace CFOrderPayResponse {
    export enum PaymentMethodEnum {
        Netbanking = <any> 'netbanking',
        Card = <any> 'card',
        Upi = <any> 'upi',
        App = <any> 'app',
        CardlessEmi = <any> 'cardless_emi',
        Paylater = <any> 'paylater'
    }
    export enum ChannelEnum {
        Link = <any> 'link',
        Collect = <any> 'collect',
        Qrcode = <any> 'qrcode'
    }
    export enum ActionEnum {
        Link = <any> 'link',
        Custom = <any> 'custom',
        Form = <any> 'form'
    }
}
