/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CFPaymentsEntityAppPayment } from './cFPaymentsEntityAppPayment';
import { CFPaymentsEntityCardPayment } from './cFPaymentsEntityCardPayment';
import { CFPaymentsEntityCardlessEMIPayment } from './cFPaymentsEntityCardlessEMIPayment';
import { CFPaymentsEntityNetbankingPayment } from './cFPaymentsEntityNetbankingPayment';
import { CFPaymentsEntityPaylaterPayment } from './cFPaymentsEntityPaylaterPayment';
import { CFPaymentsEntityUPIPayment } from './cFPaymentsEntityUPIPayment';

export class CFPaymentsEntityMethod {
    'channel': string;
    'cardNumber'?: string;
    'cardNetwork'?: string;
    'cardType'?: string;
    'cardCountry'?: string;
    'cardBankName'?: string;
    'netbankingBankCode': string;
    'netbankingBankName': string;
    'upiId'?: string;
    'provider'?: string;
    'phone'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string"
        },
        {
            "name": "cardNumber",
            "baseName": "card_number",
            "type": "string"
        },
        {
            "name": "cardNetwork",
            "baseName": "card_network",
            "type": "string"
        },
        {
            "name": "cardType",
            "baseName": "card_type",
            "type": "string"
        },
        {
            "name": "cardCountry",
            "baseName": "card_country",
            "type": "string"
        },
        {
            "name": "cardBankName",
            "baseName": "card_bank_name",
            "type": "string"
        },
        {
            "name": "netbankingBankCode",
            "baseName": "netbanking_bank_code",
            "type": "string"
        },
        {
            "name": "netbankingBankName",
            "baseName": "netbanking_bank_name",
            "type": "string"
        },
        {
            "name": "upiId",
            "baseName": "upi_id",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CFPaymentsEntityMethod.attributeTypeMap;
    }
}

