/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CFApp } from './cFApp';
import { CFAppPayment } from './cFAppPayment';
import { CFCard } from './cFCard';
import { CFCardEMI } from './cFCardEMI';
import { CFCardPayment } from './cFCardPayment';
import { CFCardlessEMI } from './cFCardlessEMI';
import { CFCardlessEMIPayment } from './cFCardlessEMIPayment';
import { CFEMIPayment } from './cFEMIPayment';
import { CFNetbanking } from './cFNetbanking';
import { CFNetbankingPayment } from './cFNetbankingPayment';
import { CFPaylater } from './cFPaylater';
import { CFPaylaterPayment } from './cFPaylaterPayment';
import { CFUPI } from './cFUPI';
import { CFUPIPayment } from './cFUPIPayment';

export class CFPaymentMethod {
    'card'?: CFCard;
    'upi'?: CFUPI;
    'netbanking'?: CFNetbanking;
    'app'?: CFApp;
    'emi'?: CFCardEMI;
    'cardlessEmi'?: CFCardlessEMI;
    'paylater'?: CFPaylater;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "card",
            "baseName": "card",
            "type": "CFCard"
        },
        {
            "name": "upi",
            "baseName": "upi",
            "type": "CFUPI"
        },
        {
            "name": "netbanking",
            "baseName": "netbanking",
            "type": "CFNetbanking"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "CFApp"
        },
        {
            "name": "emi",
            "baseName": "emi",
            "type": "CFCardEMI"
        },
        {
            "name": "cardlessEmi",
            "baseName": "cardless_emi",
            "type": "CFCardlessEMI"
        },
        {
            "name": "paylater",
            "baseName": "paylater",
            "type": "CFPaylater"
        }    ];

    static getAttributeTypeMap() {
        return CFPaymentMethod.attributeTypeMap;
    }
}

