/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CFSavedInstrumentMeta {
    /**
    * card scheme/network of the saved card
    */
    'cardNetwork'?: string;
    /**
    * Issuing bank name of saved card
    */
    'cardBankName'?: string;
    /**
    * Issuing country of saved card
    */
    'cardCountry'?: string;
    /**
    * Type of saved card
    */
    'cardType'?: string;
    'cardTokenDetails'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cardNetwork",
            "baseName": "card_network",
            "type": "string"
        },
        {
            "name": "cardBankName",
            "baseName": "card_bank_name",
            "type": "string"
        },
        {
            "name": "cardCountry",
            "baseName": "card_country",
            "type": "string"
        },
        {
            "name": "cardType",
            "baseName": "card_type",
            "type": "string"
        },
        {
            "name": "cardTokenDetails",
            "baseName": "card_token_details",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return CFSavedInstrumentMeta.attributeTypeMap;
    }
}

