/**
 * New Payment Gateway APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CFUPIAuthorizeDetails {
    /**
    * Time by which this authorization should be approved by the customer.
    */
    'approveBy'?: string;
    /**
    * This is the time when the UPI one time mandate will start
    */
    'startTime'?: string;
    /**
    * This is the time when the UPI mandate will be over. If the mandate has not been executed by this time, the funds will be returned back to the customer after this time.
    */
    'endTime'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "approveBy",
            "baseName": "approve_by",
            "type": "string"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "string"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CFUPIAuthorizeDetails.attributeTypeMap;
    }
}

