name: Trigger Tests on Pull Request.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      XCLIENTIDSANDBOX: ${{ secrets.XCLIENTIDSANDBOX }}
      XCLIENTSECRETSANDBOX: ${{ secrets.XCLIENTSECRETSANDBOX }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Check if secrets are set (masked output)
        run: |
          echo "XCLIENTIDSANDBOX is ${XCLIENTIDSANDBOX:0:4}**** (partially masked)"
          echo "XCLIENTSECRETSANDBOX is ${XCLIENTSECRETSANDBOX:0:4}**** (partially masked)"
          echo "COVERALLS_REPO_TOKEN is ${COVERALLS_REPO_TOKEN:0:4}**** (partially masked)"

      - name: Check if secrets are non-empty
        run: |
          [ -z "$XCLIENTIDSANDBOX" ] && echo "XCLIENTIDSANDBOX is empty" || echo "XCLIENTIDSANDBOX is set"
          [ -z "$XCLIENTSECRETSANDBOX" ] && echo "XCLIENTSECRETSANDBOX is empty" || echo "XCLIENTSECRETSANDBOX is set"
          [ -z "$COVERALLS_REPO_TOKEN" ] && echo "COVERALLS_REPO_TOKEN is empty" || echo "COVERALLS_REPO_TOKEN is set"

      - name: Install dependencies
        run: npm install && npm install coveralls --save-dev

      - name: Run Tests
        run: npm test && cd coverage && ls && cd .. && cat coverage/lcov.info | npx coveralls
