name: Trigger Tests on Pull Request.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      XCLIENTIDSANDBOX: ${{ secrets.XCLIENTIDSANDBOX }}
      XCLIENTSECRETSANDBOX: ${{ secrets.XCLIENTSECRETSANDBOX }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
