name: Trigger Tests on Pull Request.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      X_CLIENTID_SANDBOX: ${{ secrets.X_CLIENTID_SANDBOX }}
      X_CLIENT_SECRET_SANDBOX: ${{ secrets.X_CLIENT_SECRET_SANDBOX }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Check if secrets are set (masked output)
        run: |
          echo "X_CLIENTID_SANDBOX is ${X_CLIENTID_SANDBOX:0:4}**** (partially masked)"
          echo "X_CLIENT_SECRET_SANDBOX is ${X_CLIENT_SECRET_SANDBOX:0:4}**** (partially masked)"
          echo "COVERALLS_REPO_TOKEN is ${COVERALLS_REPO_TOKEN:0:4}**** (partially masked)"

      - name: Check if secrets are non-empty
        run: |
          [ -z "$X_CLIENTID_SANDBOX" ] && echo "X_CLIENTID_SANDBOX is empty" || echo "X_CLIENTID_SANDBOX is set"
          [ -z "$X_CLIENT_SECRET_SANDBOX" ] && echo "X_CLIENT_SECRET_SANDBOX is empty" || echo "X_CLIENT_SECRET_SANDBOX is set"
          [ -z "$COVERALLS_REPO_TOKEN" ] && echo "COVERALLS_REPO_TOKEN is empty" || echo "COVERALLS_REPO_TOKEN is set"

      - name: Install dependencies
        run: npm install && npm install coveralls --save-dev

      - name: Run Tests
        run: npm test && cd coverage && ls && cd .. && cat coverage/lcov.info | npx coveralls
