name: Trigger Tests on Pull Request.

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: CLIENT_ID=$PG_CLIENT_ID SECRET_KEY=$PG_CLIENT_SECRET npm test && yarn report && yarn coveralls
        env:
          PG_CLIENT_ID: ${{ secrets.XCLIENTIDSANDBOX }}
          PG_CLIENT_SECRET: ${{ secrets.XCLIENTSECRETSANDBOX }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
