name: Trigger Tests on Pull Request.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      XCLIENTIDSANDBOX: ${{ secrets.XCLIENTIDSANDBOX }}
      XCLIENTSECRETSANDBOX: ${{ secrets.XCLIENTSECRETSANDBOX }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: npm install && npm install coveralls --save-dev
      - name: Run Tests
        run: |
          echo "Running tests with secrets"
          npm test
          cd coverage
          ls
          cd ..
          cat coverage/lcov.info | npx coveralls
        env:
          XCLIENTIDSANDBOX: ${{ secrets.XCLIENTIDSANDBOX }}
          XCLIENTSECRETSANDBOX: ${{ secrets.XCLIENTSECRETSANDBOX }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
